// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ5AZswfZx_VxNHgkwdGnycZG8uvIq98k',
    appId: '1:521098489035:android:d7ecf256d0df3c4599bf4e',
    messagingSenderId: '521098489035',
    projectId: 'flutterdemo-328e7',
    storageBucket: 'flutterdemo-328e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuFJKWY5SXdloXzSZYGAF8ugGovTrYpyA',
    appId: '1:521098489035:ios:db07641bad1eecc699bf4e',
    messagingSenderId: '521098489035',
    projectId: 'flutterdemo-328e7',
    storageBucket: 'flutterdemo-328e7.appspot.com',
    iosClientId:
    '521098489035-8kkfqvl15gkdnm6pdn7jjpktvej8437c.apps.googleusercontent.com',
    iosBundleId: 'com.example.makemycake',
  );
}
